### ISSUE TITLE
Unable to retrieve any stock information for any devices

### ISSUE THREAD

**Issue by RetroHazard** [insanoid/iPhone-6-Store-Reserve-Monitor#12]
Unsure if this is intended behavior (if a product is out of stock), but I cannot seem to retrieve any meaningful information.  The script runs successfully using the stock config, but as soon as I modify any portion of it, I can't retrieve anything.

As such, I cannot find out the store codes near me, model numbers, or the like.
> [user@shell] ./storecheck.py
> ➜  Downloading Models List...
> ✖  No device matching your configuration was found!

My current config is:
> {
>     "country_code": "ca",
>     "device_family": "iphonex",
>     "zip_code": "T3A0E2",
>     "models":[""],
>     "carriers":[""],
>     "stores":[""]
> }

This same result occurs even when searching for hardware I can verify is available for reservation through the website.
Is this normal?

Is it possible to have the script download a catalog of products/locations even when they're not in stock so that the configuration can be more fine tuned to store/model/etc?

**Comment by RetroHazard** [comment]
I think the issue may come from the wildcard match in the carriers field. 
While testing in the US region, results failed to populate if the carrier field was blank. 

Unfortunately, the readme instructs non-US lookups to not fill this field out, likely causing the break.

**Comment by insanoid** [comment]
The problem is the blank `""` object I assume. Use this and it works!
```
{
"country_code": "ca",
"device_family": "iphonex",
"zip_code": "T3A0E2"
}
```

You can get the store ID from the result and then use it there.
