### ISSUE TITLE
TypeError: can only concatenate str (not "list") to str

### ISSUE THREAD

**Issue by lborruto** [insanoid/iPhone-6-Store-Reserve-Monitor#23]
Hello there, the script is working perfectly on my Windows machine, I tried to put it on my Debian server so it can run 24/24 and Python is throwing me this error : 

```
/usr/local/lib/python3.7/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.5) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
➜  Downloading Models List...
Traceback (most recent call last):
  File "store_checker.py", line 243, in <module>
    store_checker.refresh()
  File "store_checker.py", line 66, in refresh
    device_list = self.find_devices()
  File "store_checker.py", line 146, in find_devices
    print("----> HERE" + device_list)
TypeError: can only concatenate str (not "list") to str
```

**Comment by asyba** [comment]
> Hello there, the script is working perfectly on my Windows machine, I tried to put it on my Debian server so it can run 24/24 and Python is throwing me this error :
> 
> ```
> /usr/local/lib/python3.7/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.5) or chardet (3.0.4) doesn't match a supported version!
>   RequestsDependencyWarning)
> ➜  Downloading Models List...
> Traceback (most recent call last):
>   File "store_checker.py", line 243, in <module>
>     store_checker.refresh()
>   File "store_checker.py", line 66, in refresh
>     device_list = self.find_devices()
>   File "store_checker.py", line 146, in find_devices
>     print("----> HERE" + device_list)
> TypeError: can only concatenate str (not "list") to str
> ```

right now the store is closed, for the new Apple event today. so everything is failing.

**Comment by lborruto** [comment]
> > Hello there, the script is working perfectly on my Windows machine, I tried to put it on my Debian server so it can run 24/24 and Python is throwing me this error :
> > ```
> > /usr/local/lib/python3.7/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.5) or chardet (3.0.4) doesn't match a supported version!
> >   RequestsDependencyWarning)
> > ➜  Downloading Models List...
> > Traceback (most recent call last):
> >   File "store_checker.py", line 243, in <module>
> >     store_checker.refresh()
> >   File "store_checker.py", line 66, in refresh
> >     device_list = self.find_devices()
> >   File "store_checker.py", line 146, in find_devices
> >     print("----> HERE" + device_list)
> > TypeError: can only concatenate str (not "list") to str
> > ```
> 
> right now the store is closed, for the new Apple event today. so everything is failing.

Are you sure this is related? My Windows script is not showing any error, it just close on "Downloading Models List" (because of the maintenance).
I'll try again after the event.

**Comment by asyba** [comment]
@lborruto " , it just close on "Downloading Models List" (because of the maintenance)."
its the same issue, the script is not working as usual.

**Comment by lborruto** [comment]
> @lborruto " , it just close on "Downloading Models List" (because of the maintenance)." its the same issue, the script is not working as usual.

Working fine now, I integrated telegram-send for notification and now it's perfect!

_EDIT: found a serie 7 in stock at a third party reseller store.. So I won't be needing this again I guess._
