### ISSUE TITLE
 UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0'

### ISSUE THREAD

**Issue by RobThree** [insanoid/iPhone-6-Store-Reserve-Monitor#7]
When run with the default config.json I get the following:

    $ ./storecheck.py
    ➜  Downloading Models List...
    ✔  Found 1 devices matching your config.
    ➜  Downloading Stock Information for the devices...

    1/1 [▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉]

    Valencia Town Center, Valencia (R462)
    Traceback (most recent call last):
      File "./storecheck.py", line 127, in <module>
        print(" - {} {} ({})".format(bcolors.OKBLUE, part.get('storePickupProductTitle'), part.get('partNumber')))
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 6: ordinal not in range(128)

I tried first with a modified config:

    {
        "country_code": "nl",
        "device_family": "iphonex",
        "zip_code": "5611dk",
        "models":[],
        "carriers":[],
        "stores":[]
    }

But this also results in the same error:

    $ ./storecheck.py
    ➜  Downloading Models List...
    ✔  Found 4 devices matching your config.
    ➜  Downloading Stock Information for the devices...

    4/4 [▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉]

    Den Haag, Den Haag (R540)
    Traceback (most recent call last):
      File "./storecheck.py", line 129, in <module>
        print(" - {} {} ({})".format(bcolors.FAIL, part.get('storePickupProductTitle'), part.get('partNumber')))
    UnicodeEncodeError: 'ascii' codec can't encode character u'\u2011' in position 2: ordinal not in range(128)

**Comment by RobThree** [comment]
Narrowed it down:

This works:

    print(part.get('storePickupProductTitle'))

Output:

    256‑GB iPhone X, zilver

This doesn't:

    print("{}".format(part.get('storePickupProductTitle')))

Output:

    Traceback (most recent call last):
      File "./storecheck.py", line 135, in <module>
        print("{}".format(part.get('storePickupProductTitle')))
    UnicodeEncodeError: 'ascii' codec can't encode character u'\u2011' in position 3: ordinal not in range(128)

The dash between 256 and GB is no 'normal' dash; it's unicode char [`U+2011`](http://www.fileformat.info/info/unicode/char/2011/index.htm) and seems to cause trouble. As does `u'\xa0'` in some string somewhere with the default `config.json`.

**Comment by insanoid** [comment]
resolved in #8
